### ISSUE TITLE
No depth image and VIDIOC_DQBUF is "temporarily unavailable"

### ISSUE THREAD

**Issue by shayna34** [Terabee/linux_openni2_samples#2]
I am using the 3Dcam on a virtual machine running Ubuntu 16.04 and when I run the depth viewer sample I get a window with a blank blue screen and the following output inside my terminal. 

![image](https://user-images.githubusercontent.com/46005602/55417373-92c18480-553e-11e9-9710-9837955b2d31.png)

I suspect this has to do with the camera's configuration, as I get a similar response when running NiViewer (inside Tools/) as well as the Python sample, but I am unsure of what I would need to do to fix it. Any help on this is greatly appreciated. Thank you!

**Comment by pl-kabaradjian** [comment]
Hello @shayna34,
Unfortunately, running the sensor inside a virtual machine is beyond the scope of this repository which is focused on running sample codes. So unless their is an underlying issue with the code itself, please exchange directly with our support team (support@terabee.com) which is already handling your request (I also invite you to check your mailbox).

Have a nice day,

PS: I will leave this issue open if anyone wants to help on this topic

**Comment by shayna34** [comment]
I was able to solve it, so I will close the issue. Thank you!
