### ISSUE TITLE
Terabee Intrinsic Camera Parameters for Point Cloud Generation

### ISSUE THREAD

**Issue by azmathmoosa** [Terabee/linux_openni2_samples#4]
Hi,
I am trying to generate point cloud from the depth and IR streams.  In open3d library there is a provision to do so but it needs intrinisic camera properties.
I have looked at your spec sheet but there is no mention of focal length and other parameters.   Is it possible to share those params?
Or is there a way to generate point cloud from the camera output

**Comment by pl-kabaradjian** [comment]
Hello @azmathmoosa ,

We don't use ROS actively in Terabee anymore but I thought it was possible to use our modified [openni2_camera](https://github.com/Terabee/openni2_camera) package to generate a point cloud directly but I might be mistaken.

If that's not the case here is the expected matrix for the 3Dcam 80x60:
[55,     0,   39.5]
[  0,   55,   29.5]
[  0,     0,        1]

In the form :
[fx,     0,   cx]
[  0,   fy,   cy]
[  0,    0,    1]

Please note that depending on your device, those parameters might need to be adjusted slightly (there might be a ROS tool for that already).

If you encounter other issues, feel free to contact our support team [here](https://www.terabee.com/contact/)
